23 port matlab push recovery code to c++
wpi-huron/huron pull request #57
Opened 2023-11-02 16:12 UTC by NhiNguyencmt8

2023-11-07 17:39 UTC, dtbpkmte requested changes
Change float to double

2023-11-15 17:20 UTC, dtbpkmte commented on ros2/src/push_recovery/src/test_control.cc
> +  Ibrahim.r1_ft_force = {1,  2, 3};
Spacing, public member variables

2023-11-15 17:21 UTC, dtbpkmte commented on ros2/src/push_recovery/src/control.cc
> +  q_double_dot = SMCPOstureCorrection();
O

2023-11-15 17:24 UTC, dtbpkmte requested changes
Move push_recovery to huron/control instead of ros2

2023-11-18 00:34 UTC, NhiNguyencmt8 commented on ros2/src/push_recovery/src/test_control.cc
> +  Ibrahim.r1_ft_force = {1,  2, 3};
Si

2023-11-18 00:34 UTC, NhiNguyencmt8 commented on ros2/src/push_recovery/src/control.cc
> +  q_double_dot = SMCPOstureCorrection();
:O

2023-11-18 00:35 UTC, NhiNguyencmt8 commented
> Move push_recovery to huron/control instead of ros2

2023-11-18 00:39 UTC, dtbpkmte approved these changes

2023-11-18 00:40 UTC, merged

2023-11-18 00:41 UTC, dtbpkmte approved these changes